GET http://localhost:5299/games

###
GET http://localhost:5299/games/2

###
POST http://localhost:5299/games
Content-Type: application/json

{
    "name": "Roblox",
    "genreId": 2,
    "price": 1.00,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5299/games/5
Content-Type: application/json

{
    "name": "Street Fighter 2 Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1991-07-15"
}

###
DELETE http://localhost:5299/games/2
